org.gradle.daemon=true
org.gradle.jvmargs=-Xms512M -Xmx2G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false

android.useAndroidX=true
android.enableR8.fullMode=false

projectVersion=1.0
gdxVersion=1.14.2
kotlinVersion=2.4.20
lwjgl3Version=3.4.3
robovmVersion=2.3.26
androidPluginVersion=8.9.3
androidDesugaringVersion=2.1.5
